[package]
name = "amd_hypervisor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = []
no-assertions = []
mmap = ["log/release_max_level_off", "no-assertions"]

[dependencies]
pe = { git = "https://github.com/rust-game-hacks/driver" }
nt = { git = "https://github.com/rust-game-hacks/driver" } # TODO: Remove this
log = { git = "https://github.com/rust-game-hacks/driver" }
clean = { git = "https://github.com/rust-game-hacks/driver" }
km-alloc = { git = "https://github.com/rust-game-hacks/driver" }

snafu = { version = "0.7.0", default-features = false, features = [] }
tinyvec = { version = "1.5.1", features = ["default", "nightly_slice_partition_dedup"] }
cfg-if = "1.0.0"
obfstr = "0.3.0"
elain = "0.3.0"
bitflags = "1.3.2"
bitfield = "0.13.2"
x86 = "0.44.0"
x86_64 = { version = "0.14.7", features = ["nightly", "const_fn"] }
iced-x86 = { git = "https://github.com/icedland/iced", branch = "master", default-features = false, features = ["no_std", "decoder", "block_encoder", "instr_info", "no_d3now", "no_evex", "no_vex", "no_xop"] }
winapi = { git = "https://github.com/Trantect/winapi-rs.git", branch = "feature/km", features = ["wdm", "ntstatus"] }
static_assertions = "1.1.0"

[profile.release]
lto = "fat"
debug = true
panic = "abort"
overflow-checks = false
debug-assertions = false
