[package]
name = "amd_hypervisor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = []
no-assertions = []
mmap = ["log/release_max_level_off", "no-assertions"]
stub = []

[dependencies]
pe = { git = "https://github.com/rust-game-hacks/driver" }
nt = { git = "https://github.com/rust-game-hacks/driver" }
log = { git = "https://github.com/rust-game-hacks/driver" }
hook = { git = "https://github.com/rust-game-hacks/driver" }
clean = { git = "https://github.com/rust-game-hacks/driver" }
km-alloc = { git = "https://github.com/rust-game-hacks/driver" }
protection = { git = "https://github.com/rust-game-hacks/driver" }
bypass = { git = "https://github.com/rust-game-hacks/driver" }

snafu = { version = "0.7.0", default-features = false, features = [] }
tinyvec = { version = "1.5.1", features = ["default", "nightly_slice_partition_dedup"] }
com_logger = "0.1.0"
cfg-if = "1.0.0"
obfstr = "0.3.0"
elain = "0.3.0"
bitflags = "1.3.2"
bitfield = "0.13.2"
x86 = "0.44.0"
x86_64 = { version = "0.14.7", features = ["nightly", "const_fn", "abi_x86_interrupt", "instructions"] }
once_cell = { version = "1.9.0", default-features = false, features = ["unstable", "alloc"] }
iced-x86 = { git = "https://github.com/icedland/iced", branch = "nohashmap", default-features = false, features = ["no_std", "decoder", "block_encoder", "instr_info", "no_d3now", "no_evex", "no_vex", "no_xop", "fast_fmt"] }
winapi = { git = "https://github.com/Trantect/winapi-rs.git", branch = "feature/km", features = ["wdm", "ntstatus"] }

[profile.release]
lto = "thin"    # IMPORTANT: "fat" doesn't work and will result in an access violation
#lto = "fat"
debug = true
panic = "abort"
overflow-checks = false
debug-assertions = false
